### ISSUE TITLE
Can't download release due to Github redirect the request

### ISSUE THREAD

**Issue by taiansu** [cloudalchemy/ansible-prometheus#101]
From an unknown time, Github starts to redirect download request to AWS s3. And since using ansible `unarchive` module with `remote_src` won't follow the redirect URL, the task will actually download an HTML and report some __tar__ error like this:

```
fatal: [test -> localhost]: FAILED! => {"attempts": 1, "changed": false, "msg": "Failed to find handler for \"/private/var/folders/5m/1f26j_6d3jnbp4y30g8rhlgc0000gn/T/ansible_CxcU89/prometheus-2.2.1.linux-amd64.tar.gz\". Make sure the required command to extract the file is installed. Command \"/usr/bin/tar\" detected as tar type bsd. GNU tar required. Command \"/usr/bin/unzip\" could not handle archive."}
```

My two cents on this, and according to the discussion from https://github.com/ansible/ansible/issues/19985#issuecomment-270999632, might be split the download and unarchive into two tasks. It will be even greater if we can extract download src as an overwritable variable.

**Comment by paulfantom** [comment]
Thanks for mentioning this. I just pushed possible fix for this issue in #102, could you check if it works for you?
