### ISSUE TITLE
Get more recognition!

### ISSUE THREAD

**Issue by paulfantom** [cloudalchemy/ansible-prometheus#131]
Get more stars than https://github.com/William-Yeh/ansible-prometheus and be listed higher than that role in ansible galaxy.

:gem: :gem: :gem:

**Comment by paulfantom** [comment]
First success!

![screenshot_20180806_113435](https://user-images.githubusercontent.com/3531758/43709364-e668e864-996c-11e8-9367-ec7110c58848.png)

Screenshot taken with browser in incognito mode.

**Comment by aditya-konarde** [comment]
Excellent work guys, I really like what you have done here. I'm going to recommend this repo to anyone who's looking at deploying Prometheus via Ansible. Keep up the good work!

**Comment by paulfantom** [comment]
Done! 240 stars which is one more than repo mentioned in a first commit :tada: 
Many thanks to all who made this happen!

I am closing this as a main goal is already reached, but development will still continue :smile:
