### ISSUE TITLE
No Support for pre-systemd os init service

### ISSUE THREAD

**Issue by gaizeror** [cloudalchemy/ansible-prometheus#139]
We are using Amazon Linux1 (Centos 6) and there is no Support for systemd.
We need help with init.d script

**Comment by paulfantom** [comment]
Sorry, lack of support for non-systemd was intentional as we are using systemd features for security of prometheus installation.

**Comment by paulfantom** [comment]
Mainly those things: https://github.com/cloudalchemy/ansible-prometheus/blob/08c87a7fc707ab289c6006f2a3f84bbff793d2c4/templates/prometheus.service.j2#L22-L38
