### ISSUE TITLE
prometheus_alert_rules are not copied as expected

### ISSUE THREAD

**Issue by arjuntoor1** [cloudalchemy/ansible-prometheus#148]
Hello, I am having problems with setting up default alerts in configuration.

Version: 2.3.3

<hr />

#### Expected behaviour
When the `prometheus_alert_rules` file is populated with some rules, and I then provision the instance, a file should be created in `{{ prometheus_config_dir }}/rules/basic.rules` containing those rules.

#### Actual behaviour
The `{{ prometheus_config_dir }}/rules/` directory exists but is empty, and Prometheus sees no alerts configured.   This occurs even if I simply use the [default value for `prometheus_alert_rules`](https://github.com/cloudalchemy/ansible-prometheus/blob/master/defaults/main.yml#L69)

<hr />

Other properties I am using (for example, `prometheus_scrape_configs` and `prometheus_alertmanager_config`) seem to work just fine.

**Comment by paulfantom** [comment]
Alerting rules are copied to `{{ prometheus_config_dir }}/rules/ansible_managed.rules` when there are two variables set:
- `prometheus_alert_rules`
- `prometheus_alertmanager_config`

We figured there is no need to create alerting rules when you don't have alertmanager configuration.

**Comment by arjuntoor1** [comment]
Ah, I see.  I had not provided `prometheus_alertmanager_config` since I was just trying to get the rules written to the file.  This morning I moved on to AlertManager and now it works.

It would be good if it printed a message just like yours, i.e. "_no need to create alerting rules when you don't have alertmanager configuration_", in this case.
