### ISSUE TITLE
Default rules not working correctly

### ISSUE THREAD

**Issue by sjal** [cloudalchemy/ansible-prometheus#157]
With the defaults now as they are CPU,RAM and DiskSpace alerts needs to be reworked.

eg.
`(100 * (1 - avg(irate(node_cpu{job="node",mode="idle"}[5m])) BY (instance))) > 96
`
won't work, but
`100 - (avg by (instance) (irate(node_cpu_seconds_total{job="node",mode="idle"}[5m])) * 100) > 96`
will

I think the PromQL just changed as I remember those defaults to be working correctly (unless I am missing something and the first one is ok).

**Comment by paulfantom** [comment]
@SuperQ could you look at those expressions?

**Comment by sjal** [comment]
I've checked the rest just now.
CriticalRAMUsage is:
`(1 - ((node_memory_MemFree + node_memory_Buffers + node_memory_Cached) / node_memory_MemTotal)) * 100 > 98`
should be:
`(1 - ((node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) / node_memory_MemTotal_bytes)) * 100 > 98`

CriticalDiskSpace is:
`node_filesystem_free{job="node",filesystem!~"^/run(/|$)"} / node_filesystem_size{job="node"} < 0.1`
should be:
`node_filesystem_free_bytes{environment="production",filesystem!~"^/run(/|$)"} / node_filesystem_size_bytes{environment="production"} < 0.1`

**Comment by SuperQ** [comment]
The expressions are fine, but the metric names have changed.

**Comment by sjal** [comment]
> The expressions are fine, but the metric names have changed.

That's the point
