### ISSUE TITLE
Wrong home directory for the prometheus user

### ISSUE THREAD

**Issue by ptselios-inmarsat** [cloudalchemy/ansible-prometheus#166]
The home directory of the prometheus user is /tmp. 
Since this is a system user the home directory should either be the directory of the application or the /dev/null.

**Comment by paulfantom** [comment]
Previously it wasn't set to anything, but after https://github.com/cloudalchemy/ansible-prometheus/issues/153 we changed this behavior. 

@michalklempa Would `/dev/null` as prometheus user home directory will work on GCE?

**Comment by ptselios-inmarsat** [comment]
Meaning, if I already have prometheus up and running and run the playbook again, it will fail since the ansible's user module will try to chmod the user's home directory and it will fail since the home directory will be /home/prometheus, it tries to change it to /tmp and prometheus is running...

**Comment by paulfantom** [comment]
Oh, so this is a problem with an upgrade path and not with result itself, got it. I will and a warning in readme and release notes about this problem with a simplest possible solution:
> switch prometheus off before an upgrade

**Comment by ptselios-inmarsat** [comment]
Hmmm
It's not that simple, unfortunately. I removed my AWS instances and recreated them from scratch. 
It failed. 
Also, I just run the playbook in order to make sure that the systems are in the desired state. It failed again. 
My solution was manually change the entry in the /etc/passwd

**Comment by paulfantom** [comment]
That is strange. We are running automated daily deployments of our roles against one server (demo.cloudalchemy.org) and it didn't show any signs of problems. As a test I just run this role against vanilla fedora 29 server in digital ocean and it also went ok.

**Comment by ptselios-inmarsat** [comment]
My setup is CentOS 7 in AWS deployed through Ansible Tower 3.3.1
