### ISSUE TITLE
Executable HTML files in consoles and console_libraries in prometheus_config_dir

### ISSUE THREAD

**Issue by dreig** [cloudalchemy/ansible-prometheus#168]
The html files in `/etc/prometheus/consoles` and `/etc/prometheus/console_libraries` get copied with 755 (executable) permissions. They should have mod 0644 instead.
```
vagrant@ubuntu:~$ sudo ls -la  /etc/prometheus/consoles
total 44
drwxr-xr-x 2 root root       4096 Dec 26 12:45 .
drwxr-x--- 7 root prometheus 4096 Dec 26 12:45 ..
-rwxr-xr-x 1 root root        623 Dec 26 12:45 index.html.example
-rwxr-xr-x 1 root root       2675 Dec 26 12:45 node-cpu.html
-rwxr-xr-x 1 root root       3513 Dec 26 12:45 node-disk.html
-rwxr-xr-x 1 root root       1444 Dec 26 12:45 node.html
-rwxr-xr-x 1 root root       5794 Dec 26 12:45 node-overview.html
-rwxr-xr-x 1 root root       1332 Dec 26 12:45 prometheus.html
-rwxr-xr-x 1 root root       4128 Dec 26 12:45 prometheus-overview.html
```
I also think that the owner/group of these files should be prometheus instead of root. Would that be appropriate?

**Comment by paulfantom** [comment]
Those should have 0644 permissions. I don't see any reason why they should be owned by prometheus user.

This should be an easy fix as only this line needs to be modified: https://github.com/cloudalchemy/ansible-prometheus/blob/master/tasks/install.yml#L78 could you create a PR and test it?

**Comment by dreig** [comment]
Sure, I'll submit the PR tonight.
