### ISSUE TITLE
Allow specifying source url for Prometheus archive

### ISSUE THREAD

**Issue by luminouw** [cloudalchemy/ansible-prometheus#176]
Hi there,

currently working for a client with a highly restricted environment, as in controllers and nodes cannot access the outside world. They want to rely as much as possible on existing and maintained Ansible roles without having to tweak the tasks and use variables as much as possible.

Long story short, they host tar.gz releases internally and don't want to do nasty stuff like lying DNS servers redirecting traffic aimed at Github or anywhere else to internal servers.

Question is, would it be possible to have the variables related to external stuff moved to the defaults/main.yml file and use variables in the tasks, allowing the user to specify their own location ? 

I see you're making use of the `delegate_to: localhost` directive so only the controller needs access to Github, and I'm still trying to convince them that it's going to be a nightmare to ask every Ansible role developer to allow url overwriting.

Have you ever seen such cases with that much limited connectivity and how do you usually do ?

Thanks : )

**Comment by paulfantom** [comment]
The `delegate_to: localhost` was done specially for use cases where target hosts doesn't have direct access or have very limited access to internet.

Another design decision was to embed links to binaries in ansible role and do not provide any way to override those, but add checksum validations to ensure consistency of downloaded packages. This mechanism is used across all cloudalchemy roles which download binaries directly and it was additionally extended to automatically support multi-arch deployments.

> would it be possible to have the variables related to external stuff moved to the defaults/main.yml file

It would be possible, but it is not so simple as urls are calculated during execution.

**Comment by luminouw** [comment]
Alright, thanks for the heads up !

On my way for listing all the pros and cons of having your controller able to access packages and level up on the speech skill to persuade them : )
