### ISSUE TITLE
Does not clean alerts catalogue

### ISSUE THREAD

**Issue by gecube** [cloudalchemy/ansible-prometheus#180]
Good day!

I tried to use the latest version of this role and it is awesome! But I faced with a very pity issue:
I removed the alert rule file from ./prometheus/rules catalogue and re-ran the playbook. The old alert rule file was left on the target server. I believe that the desired behaviour is to clean /etc/prometheus/rules catalogue on the target server from the files that are absent in ansible inventory.

I removed the obsoleted file on the target host by hand and re-ran the playbook,. Unfortunately it didn't detect the changes and so the alert list in Prometheus was old, so it forced me to restart the service manually too. :-(

**Comment by paulfantom** [comment]
We are not doing file synchronization (the way rsync does it) and we have no plans on providing any means of uninstallation which means that this is out of project scope.
