### ISSUE TITLE
Implement Uninstalls based on specific variables

### ISSUE THREAD

**Issue by aditya-konarde** [cloudalchemy/ansible-prometheus#181]
The way the current playbook is set up, does not allow for shutting down/uninstalling the Prometheus server. 

We should allow this, so that we can close out an old server if we're moving to a new one.

**Comment by paulfantom** [comment]
I have never seen such option in any ansible role. But this might be a good one.

**Comment by SuperQ** [comment]
IMO, this is against how modern config management is done. All ansible/chef/etc configuration I've ever seen does install-only. The only way to remove is to wipe a machine.

To do more than this, you need something like Kubernetes. :)

**Comment by paulfantom** [comment]
We have no plans on providing any means of uninstallation which means that request is out of project scope.

**Comment by aditya-konarde** [comment]
Sorry to come back late to the party, but I essentially agree that this isn't needed :)
