### ISSUE TITLE
can't create prometheus user again

### ISSUE THREAD

**Issue by gecube** [cloudalchemy/ansible-prometheus#185]
If there is another prometheus installation in `/opt/prometheus` and the service prometheus is started, the playbook can't create the user prometheus again:

`TASK [cloudalchemy.prometheus : create prometheus system user] *********************************************************************************************************************************************
fatal: [nexus]: FAILED! => {"changed": false, "msg": "usermod: user prometheus is currently used by process 25091\n", "name": "prometheus", "rc": 8}`

In fact, the user is already created and used by running process.

The solution is to stop the prometheus service and try again. I believe that the playbook can detect the such situation and automatically resolve it.

**Comment by gecube** [comment]
I believe you are right. I want to emphasize that I don't upgrade the role itself. I upgraded the prometheus (unfortunately, I lost the old version number). Maybe - is it good idea to fix the documentation?

**Comment by paulfantom** [comment]
If you changed only `prometheus_version` variable and didn't change anything in a role between runs then it shouldn't affect you since task "create prometheus system user" is idempotent.
The only way this can be happening is if you are changing configuration for a prometheus user on target host between runs. In such scenario this role will try to revert those changes but it will fail with the error you pasted. I would say that this information shouldn't be hidden by automation as this is quite important message which should result into looking more closely what happened and what was the reason user was modified.

**Comment by gecube** [comment]
One more addition: the first instance of prometheus was manually installed, not by the role. If it matters anything... The issue is that the role remove all /opt/prometheus contents and the ordering of operations (or - tasks) is important, so maybe it is good idea to write some more comprehensive messages what is going on.

Thank you for your kind comments.

**Comment by paulfantom** [comment]
I think this might be time to remove a task responsible for removal of `/opt/prometheus`. This was implemented as we were transitioning between using `/opt` and using `/usr/local/` but I think this transition is complete.

Could you create a PR removing that task?

**Comment by gecube** [comment]
I had another side-effect. We are using convention that all stuff that is installed by our developers usually is located in `/opt` catalogue. So the case:
1. the developer installs the prometheus in `/opt/prometheus` and place there configs
2. I want to reinstall it via your great role
3. I stop the prometheus to prevent undesired side-effects
4. apply the role
5. and I see that the `/opt/prometheus` is removed with all it's content (configs etc.). There is no explicit note in documentation that the role remove this catalogue. This is the issue. Of course, if I'd know, I backed files up :-)

 

So the correct flow looks like this:

1. check that the prometheus is installed as systemd
2.1. if no - proceed
2.2. if yes - check the path to the configs and the executable
2.2.1. if the path is /opt/prometheus - two options - show error OR stop service, remove configs and proceed further
2.2.2. if the path is the default of role - proceed further.

@paulfantom what do you think? Will it be super-complication or no?

**Comment by paulfantom** [comment]
> 1. check that the prometheus is installed as systemd
   2.1. if no - proceed
   2.2. if yes - check the path to the configs and the executable
   2.2.1. if the path is /opt/prometheus - two options - show error OR stop service, remove configs and proceed further
   2.2.2. if the path is the default of role - proceed further.

If we remove task responsible for removal of `/opt/prometheus` I don't really see a reason to implement what you describe.
