### ISSUE TITLE
Support recording rules without alerts

### ISSUE THREAD

**Issue by jws305** [cloudalchemy/ansible-prometheus#192]
It doesn't seem there is a straight forward way to use recording rules with this playbook.  You can specify them as part of the alerting rules but there is a conditional on task that manages alert rules which stops it if no `prometheus_alertmanager_config` is specified.

https://github.com/cloudalchemy/ansible-prometheus/blob/ff7830d06ba57be1177f2b6fca33a4dd2d97dc20/tasks/configure.yml#L2-L14

I was able to work around this by adding a stub alerting rule
```yaml
prometheus_alertmanager_config:
  - timeout: 10s
```

https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/

**Comment by paulfantom** [comment]
Sorry for delay. Could you create a PR with a fix? It seems pretty easy to do.
