### ISSUE TITLE
FAILED: parsing YAML file 

### ISSUE THREAD

**Issue by ben-le** [cloudalchemy/ansible-prometheus#195]
I got the same syntax error with the existing issue "failed to parsing YAML File #129" 
when running the playbook.

TASK [cloudalchemy.prometheus : configure prometheus] *************************************************************************************************************
Wednesday 20 March 2019  19:29:06 +0000 (0:00:00.061)       0:00:25.019 ******* 
fatal: [monitor.example.com]: FAILED! => {"changed": false, "checksum": "083e5057d0bf958f87ce817aab84c86579897d4e", "exit_status": 1, "msg": "failed to validate", "stderr": "  FAILED: parsing YAML file /home/ben.le/.ansible/tmp/ansible-tmp-1553110147.04-172617959679310/source: yaml: **unmarshal errors:\n  line 23: cannot unmarshal !!str `labs-al...` into struct** { Targets []string \"yaml:\\\"targets\\\"\"; Labels model.LabelSet \"yaml:\\\"labels\\\"\" }\n", "stderr_lines": ["  FAILED: parsing YAML file /home/ben.le/.ansible/tmp/ansible-tmp-1553110147.04-172617959679310/source: yaml: unmarshal errors:", "  line 23: cannot unmarshal !!str `labs-al...` into struct { Targets []string \"yaml:\\\"targets\\\"\"; Labels model.LabelSet \"yaml:\\\"labels\\\"\" }"], "stdout": "Checking /home/ben.le/.ansible/tmp/ansible-tmp-1553110147.04-172617959679310/source\n\n", "stdout_lines": ["Checking /home/ben.le/.ansible/tmp/ansible-tmp-1553110147.04-172617959679310/source", ""]}

It was complaining the line "23" in the prometheus.yml

Here's the Prometheus file:

global:
  evaluation_interval: 15s
  scrape_interval: 15s
  scrape_timeout: 10s

  external_labels:
    {}

rule_files:
  - /etc/prometheus/rules/*.rules

alerting:
  alertmanagers:
  - scheme: https
    static_configs:
    - targets:
      - alertmanager.example.com

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
    - targets:
      - monitor.example.com:9090
  - file_sd_configs:
    - files:
      - /etc/prometheus/file_sd/node.yml
    job_name: node
    relabel_configs:
    - regex: (.*):9100
      replacement: ${1}
      source_labels:
      - __address__
      target_label: instance
    scrape_interval: 20s

**Comment by paulfantom** [comment]
Please format your message with markdown ([link to a nice guide](https://guides.github.com/features/mastering-markdown/)) otherwise I don't know what is the indentation in your config.

**Comment by ben-le** [comment]
@paulfantom, please review the prometheus.txt file to see the correct indentation. 
[prometheus.txt](https://github.com/cloudalchemy/ansible-prometheus/files/2990054/prometheus.txt)

**Comment by paulfantom** [comment]
Could you also attach `prometheus_scrape_configs` values?

**Comment by JordanP** [comment]
FWIW `cannot unmarshal !!str labs-al... into struct { Targets []string ` is a typical Go unmarshal error (i.e not Python/Ansible related)

**Comment by paulfantom** [comment]
I agree it is not python/ansible related. It is specific to this role, I think there is some misconfiguration in `prometheus_scrape_config` and `promtool` cannot handle new config. This in turn causes failure to run a role (expected behavior).

**Comment by ben-le** [comment]
Please review the attached file
[prometheus.yml.txt](https://github.com/cloudalchemy/ansible-prometheus/files/2992698/prometheus.yml.txt)

**Comment by paulfantom** [comment]
I need your ansible variables, not prometheus.yml file.

**Comment by ben-le** [comment]
[monitor.txt](https://github.com/cloudalchemy/ansible-prometheus/files/2993557/monitor.txt)

**Comment by ben-le** [comment]
Attached is the ansible variables for my monitor.
[monitor.txt](https://github.com/cloudalchemy/ansible-prometheus/files/2993563/monitor.txt)

**Comment by paulfantom** [comment]
Sadly I don't see what is wrong. You can try running [ansible playbook debugger](https://docs.ansible.com/ansible/latest/user_guide/playbooks_debugger.html) to get `prometheus.yml` file created by this role and then running that file through `promtool` to check what is wrong.
Other solution would be to run this role with prometheus config validation removed (https://github.com/cloudalchemy/ansible-prometheus/blob/de31ec64e4bf789793528849b36b554687538302/tasks/configure.yml#L36) and manually checking what is wrong.
