### ISSUE TITLE
Default CriticalDiskSpace alert using wrong label?

### ISSUE THREAD

**Issue by mjbnz** [cloudalchemy/ansible-prometheus#201]
Looks like it's using the `filesystem` label, not `mountpoint`, or am I misunderstanding?

[Link to line in `defaults/main.yml` here](https://github.com/cloudalchemy/ansible-prometheus/blob/645988540b86c14c5ce78ac582dc5dc0d524c2e4/defaults/main.yml#L111)

After changing the expression to:
```
node_filesystem_free_bytes{mountpoint!~"^/(snap|run)(/.*|$)",job="node"} / node_filesystem_size_bytes{job="node"} < 0.1
```
things work a little better for me (that also ignores snap mounts from ubuntu systems, and adds `.*` after `/`, as subdirs of `/run` weren't matching without it).

**Comment by paulfantom** [comment]
You are right it should be using `mountpoint` label. I think this alert was correct for older node_exporter versions as there was a change in label names at some point.

Could you create a PR with a fix?

**Comment by mjbnz** [comment]
Done!

**Comment by mjbnz** [comment]
So, looking at it, a better option is to not look at `mountpoint` at all, but use `fstype`:

`fstype!~"(tmpfs|squashfs|fuse.*)"`

I've amended the PR to use that.

**Comment by paulfantom** [comment]
> So, looking at it, a better option is to not look at mountpoint at all, but use fstype

It is, but without `tmpfs` [[more info](https://github.com/cloudalchemy/ansible-prometheus/pull/202#issuecomment-486185496)]. `squashfs` and `fuse` are a nice touch :+1:
