### ISSUE TITLE
error when using the role

### ISSUE THREAD

**Issue by bngsudheer** [cloudalchemy/ansible-prometheus#210]
TASK [cloudalchemy.prometheus : create prometheus system user] ****************************************************************************************************************************************************
fatal: [h5.gavika.com]: FAILED! => {"changed": false, "msg": "usermod: user prometheus is currently used by process 29482\n", "name": "prometheus", "rc": 8}

To workaround this, I had to stop prmetheus server and run Ansible.

**Comment by paulfantom** [comment]
This was communicated via [release notes for 2.4.1](https://github.com/cloudalchemy/ansible-prometheus/releases/tag/2.4.1) and a note is placed in Readme file. If this problem persists please reopen with more details.

**Comment by bngsudheer** [comment]
Thanks. I missed the release notes for 2.4.1. It is not clear what steps have to be taken to resolve this permanently. I keep getting this error every now and then. From the release notes, I would assume this error should occur only once during the upgrade?

**Comment by paulfantom** [comment]
Yes, this should occur only once when upgrading system which was provisioned with role in version <2.4.0 to provisioning with role in version >=2.4.1.

We don't see any error with our daily provisioning in https://github.com/cloudalchemy/demo-site.
