### ISSUE TITLE
Add Thanos components

### ISSUE THREAD

**Issue by SuperQ** [cloudalchemy/ansible-prometheus#235]
It would be useful to add Thanos components to the cloudalchemy roles.

CC @bwplotka :smile:

**Comment by bwplotka** [comment]
Wow, I just learned that this exists, this is epic!

**Comment by erikgb** [comment]
I am looking at how to add Thanos sidecar to our Prometheus installation, and is already using (a modified version) of this role to install Prometheus. Would you be interested in considering a PR adding Thanos sidecar as an optional feature to this role? It could be a small step towards resolving this issue. But I do not have the knowledge nor bandwidth to create new roles for the rest of the Thanos ecosystem....

**Comment by DEvil0000** [comment]
when you search for roles to thanos you will find at least 5 and at least 2 good ones.
I use this one (or actually a fork) which fits my needs best:
https://github.com/CVi/ansible_thanos

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**
