### ISSUE TITLE
Download process for binaries 

### ISSUE THREAD

**Issue by th31nitiate** [cloudalchemy/ansible-prometheus#245]
I love the playbook it works perfectly and I truly appreciate the work. I have a question around the download process. I understand that it downloads and works with archives locally. 

I was wondering why you do not download the archives in the remote system. This some like for some it would be a suitable solution. I can understand the requirement for your method when working in air gap like networks or when you have multiple nodes. 

In my current environment it may be beneficial to have the choice of both. Please let me know if you would be interested in PR to add a toggle ?

**Comment by paulfantom** [comment]
There are multiple reasons for downloading binary to deployer host and propagating it:
1) easier to deploy in air-gap networks
2) download once - propagate to many scales well in systems with multiple hosts. This may not be ideal for prometheus itself and more necessary for things like node-exporter. But for the sake of simplicity and easier maintainability we didn't want to diverge.
3) code reuse for propagating custom binaries (flag `prometheus_binaries_local_dir`). Which means installation path is the same for custom binary and "official" ones and that gives us better test coverage.

What would be the benefit of doing it directly on target host without downloading binary to deployer host beforehand?

**Comment by th31nitiate** [comment]
You are right. I suppose the model I am using at the moment is not generally ideal. This is because there is no deployer machine rather my local system. This means that I am possibly limited by the network connection on my local system. 

I suppose this would be beneficial in bashton based environment or one with deployer machine responsible for running state. Which I have seen before but never re-implemented.

**Comment by paulfantom** [comment]
You shouldn't have much network performance penalty in model you are describing. This is literally what we are doing for our demo-site, where deployer host is ephemeral so state (binaries) isn't preserved. In such model ansible will download package to localhost, but it won't propagate to other hosts if local and remote binary checksum match. Which means only runs changing binaries are affected by network bandwidth and other changes are not affected.

I am closing this as process is established and feature won't be implemented.

----
Just to clarify for future readers: deployer/master/controller model, this is fairly common approach and used for example by OpenStack-Ansible project or in any deployment with Ansible Tower.
