### ISSUE TITLE
Download binary [SSL: CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by js-max** [cloudalchemy/ansible-prometheus#247]
Unable to proceed with binary download as expected.

**Default vars used:**
`prometheus_version: 2.14.0`

**File:** 

> cloudalchemy.prometheus/tasks/install.yml

**Task:** 

> download prometheus binary to local folder

**Failed to download:**

`FAILED! => {"attempts": 5, "changed": false, "dest": "/tmp/prometheus-2.14.0.linux-amd64.tar.gz", "elapsed": 0, "msg": "Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>", "url": "https://github.com/prometheus/prometheus/releases/download/v2.14.0/prometheus-2.14.0.linux-amd64.tar.gz"}`

As **workaround** added:
`validate_certs: false`

It's as supposed to?

KR

**Comment by paulfantom** [comment]
Failures in certificate validations are transient errors cause either by outdated CA certs on your host or are associated with network problems. `validate_certs: false` promote security bad practices. Role uses default ansible plugins and contacts well-established domain (github.com) and as such, I don't see any work to be done in this role.

If the problem persists in your scenario and you don't want to dwell into why there are problems with certs in your environment, you can use `prometheus_binaries_local_dir` feature.

**Comment by js-max** [comment]
Thanks for the feedback!
