### ISSUE TITLE
Possible to use ec2_sd_configs for automatic service discovery?

### ISSUE THREAD

**Issue by alanmcg** [cloudalchemy/ansible-prometheus#262]
Is it possible to use service discovery to populate the list of targets with this role? Been scratching my head trying to figure out how this can work.

**Comment by rdemachkovych** [comment]
You can try to add your job with [<ec2_sd_config>](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#ec2_sd_config) to `prometheus_scrape_configs` varibels as is in [`defaults`](https://github.com/cloudalchemy/ansible-prometheus/blob/cdd450c995c0794d188a6e4e3c1a0cc9a44b6576/defaults/main.yml#L65)

**Comment by paulfantom** [comment]
As @rdemachkovych said, just put it into `prometheus_scrape_configs` variable, the same way it is specified in prometheus docs for `scrape_configs`.

Following is just a basic template which can be tweaked:
```
prometheus_scrape_configs:
  - job_name: ec2
    ec2_sd_configs:
    - filters:
      [ - name: <string>
          values: <string>, [...] ]
      [ region: <string> ]
      [ endpoint: <string> ]
      [ access_key: <string> ]
      [ secret_key: <secret> ]
      [ profile: <string> ]
      [ role_arn: <string> ]
      [ refresh_interval: <duration> | default = 60s ]
      [ port: <int> | default = 80 ]
```

**Comment by alanmcg** [comment]
Thanks, this worked great
