### ISSUE TITLE
Allow texteditors highlight rules based on extention

### ISSUE THREAD

**Issue by freeseacher** [cloudalchemy/ansible-prometheus#268]
**What is missing?**
For now alerts have to be with extension `.rules`
https://github.com/cloudalchemy/ansible-prometheus/blob/015db753b1ab334a6669b3045c125088bfb4c5ef/templates/prometheus.yml.j2#L21

that disables syntax highlight for most text editors. Please change it to `*.rules.yml` 

**Why do we need it?**
It looks like basic user attention.

**Comment by freeseacher** [comment]
probably introducing default with that kind of line
`prometheus_rule_files: "{{ prometheus_config_dir }}/rules/*.rules"`
looks like reasonable solution

**Comment by paulfantom** [comment]
That makes sense to me. Maybe we can provide both for backwards compatibility? Can you create PR?

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**
