### ISSUE TITLE
Demo site does not load

### ISSUE THREAD

**Issue by juanrosero** [cloudalchemy/ansible-prometheus#278]
**What happened?**
Demo site, https://demo.cloudalchemy.org does not load on Web browser.
**Did you expect to see some different?**

**How to reproduce it (as minimally and precisely as possible)**:
Point Web browser to https://demo.cloudalchemy.org and hit the [Return/Enter] key.
**Environment**

* Role version:

    `Insert release version/galaxy tag or Git SHA here`

* Ansible version information:

    `ansible --version`
    

* Variables:

```
insert role variables relevant to the issue
```

* Ansible playbook execution Logs:

```
insert Ansible logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by paulfantom** [comment]
As said in https://github.com/cloudalchemy/demo-site#deprecation-notice cloudalchemy demo site was deprecated in favor of https://demo.do.prometheus.io
