### ISSUE TITLE
conf.d folder is provided, but there is no mechanism for using it

### ISSUE THREAD

**Issue by abeluck** [cloudalchemy/ansible-prometheus#283]
**What happened?**

This role creates This role creates `/etc/prometheus/conf.d``, but there is no mechanism for having files in this directory included in the prometheus configuration.

**Did you expect to see some different?**
I expected files in `/etc/prometheus/conf.d` to work.

**How to reproduce it (as minimally and precisely as possible)**:

1. Run this role
2. Template out a file to  `/etc/prometheus/conf.d`

**Environment**

debian 10 

* Role version:

2.15.1

* Ansible version information:

ansible 2.9.6
python 3

* Variables:

n/a

* Ansible playbook execution Logs:

n/a

**Comment by paulfantom** [comment]
That directory should be removed. Can you create a PR?

**Comment by abeluck** [comment]
Deleting that line will prevent the role from creating that directory on new runs.

Should the role delete existing directories?

**Comment by paulfantom** [comment]
> Should the role also delete existing directories?

No, because users could already configure their instances to have something there and reference it via custom scrape jobs.
