### ISSUE TITLE
Old rule files not removed/renamed when redeploying

### ISSUE THREAD

**Issue by wikro** [cloudalchemy/ansible-prometheus#287]
**What did you do?**
Changed the name of a rule file, deleted an unnecessary rule file, and redeployed. This resulted in having two sets of the renamed file: one with the old filename, and one with the new filename. The deleted file was still present on the host.

**Did you expect to see some different?**
Expected the deleted file to be removed from the host, and the file with the old filename to be removed, or renamed, to reflect the changes made to the rule files in the repo.

**Environment**

* Variables:

```
prometheus_alert_rules_files
```

**Anything else we need to know?**:
If this is intended behaviour, is there a reasoning behind it?

**Comment by paulfantom** [comment]
Yes, this is intended behavior. There is no way of knowing if the deployed rule file was added via this role or via any other system (for example as a post-job, like here: https://github.com/prometheus/demo-site/blob/master/.circleci/config.yml). Hence this role doesn't manage removal of rule files.
