### ISSUE TITLE
Intermitent slow deploy times 

### ISSUE THREAD

**Issue by tomasaberg** [cloudalchemy/ansible-prometheus#288]
**What did you do?**
Hi and thanks a lot for this great role!

When we deploy and a new release of prometheus(server, node_exporter, blackbox and so on) is available and the role download the new release, we've seen that our download speed is being throttled to ~5kb/s, making the deploy take up to 15-20 minutes. This is a intermittent issue and I guess the issue is rather with GitHub.

I suppose we could use the variables `prometheus_binary_local_dir`, `alertmanager_binaries_local_dir` etc but I'm not sure how we should or could sync the content of the releases on Prometheus github page. Do you have any suggestion to this issue?

**Did you expect to see some different?**
Not being throttled

**Environment**
Production, Stage, Dev

* Role version:

    master

* Ansible version information:

Ansible Tower 3.6.2 
Ansible 2.9.4

* Variables:
-

* Ansible playbook execution Logs:
-

**Anything else we need to know?**:
-

**Comment by paulfantom** [comment]
If you are deploying from one deployer host, then using `prometheus_binary_local_dir` and syncing binaries can be done with a cronjob. You can look for more inspiration in our e2e tests, specifically this playbook: https://github.com/cloudalchemy/ansible-prometheus/blob/master/molecule/alternative/prepare.yml.
