### ISSUE TITLE
Molecule error

### ISSUE THREAD

**Issue by furbaez** [cloudalchemy/ansible-prometheus#294]
**What happened?**
When I run molecule I am getting and error 
**Did you expect to see some different?**

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Role version:

    `master`

* Ansible version information:

    `ansible --version`
    

* Ansible playbook execution Logs:

```
 fatal: [centos7 -> localhost]: FAILED! => {"changed": false, "msg": "Failed to find handler for \"/root/.ansible/tmp/ansible-tmp-1589987489.6133811-51729961650313/source\". Make sure the required command to extract the file is installed. Command \"/usr/bin/unzip\" could not handle archive. Command \"/bin/tar\" detected as tar type None. GNU tar required."}

```

**Anything else we need to know?**:

**Comment by paulfantom** [comment]
> GNU tar required

On Mac you need gnu-tar (`brew install gnu-tar`) as written in [requirements section of README.md](https://github.com/cloudalchemy/ansible-prometheus#requirements)

**Comment by furbaez** [comment]
I am not running this on a Mac, I am running this inside a Centos:7 docker container

**Comment by furbaez** [comment]
@paulfantom Could you please advise if you can I am not using a Mac.

**Comment by paulfantom** [comment]
Try installing `tar` utility

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**
