### ISSUE TITLE
prometheus_storage_retention_size flag does not work

### ISSUE THREAD

**Issue by jomach** [cloudalchemy/ansible-prometheus#295]
**What happened?**
The flag prometheus_storage_retention_size does not work

**Did you expect to see some different?**

**How to reproduce it (as minimally and precisely as possible)**:
- name: Setting up prometheus
  import_role:
    name: cloudalchemy.prometheus

* Role version:

    `https://github.com/cloudalchemy/ansible-prometheus/releases/tag/2.15.5`

* Ansible version information:

    `ansible 2.9.9
  config file = /Users/jorge/.ansible.cfg
  configured module search path = ['/Users/jorge/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.2 (default, Mar 11 2020, 00:29:50) [Clang 11.0.0 (clang-1100.0.33.17)]`

* Variables:

```
prometheus_storage_retention_size: "1TB"
prometheus_version: 2.19.0
```

* Ansible playbook execution Logs:
the file /etc/systemd/system/prometheus.service looks like this: 
```Group=prometheus
ExecReload=/bin/kill -HUP $MAINPID
ExecStart=/usr/local/bin/prometheus \
  --config.file=/etc/prometheus/prometheus.yml \
  --storage.tsdb.path=/var/lib/prometheus \
  --storage.tsdb.retention.time=30d \
  --storage.tsdb.retention.size=0 \
  --web.console.libraries=/etc/prometheus/console_libraries \
  --web.console.templates=/etc/prometheus/consoles \
  --web.listen-address=0.0.0.0:9090 \
  --web.external-url=
CapabilityBoundingSet=CAP_SET_UID
```

**Anything else we need to know?**:
I think the 
{% if prometheus_version is version('2.7.0', '>=') %} is wrong

**Comment by paulfantom** [comment]
> {% if prometheus_version is version('2.7.0', '>=') %} is wrong

This is working correctly. Without it, ansible would create only:
```
  --storage.tsdb.retention=30d \
```
instead of
```
  --storage.tsdb.retention.time=30d \
  --storage.tsdb.retention.size=0 \
```

Note to self: we should probably invert that version check.
---

Seems like ansible took value from [defaults/main.yml#L16]( https://github.com/cloudalchemy/ansible-prometheus/blob/master/defaults/main.yml#L16)

You may need to re-check for potential typos and verify if your settings were applied (https://docs.ansible.com/ansible/latest/user_guide/playbooks_debugger.html#on-a-play)

**Comment by jomach** [comment]
this could be maybe because I import the role from other playbook.... closing then. Thanks for the tipp.
