### ISSUE TITLE
offline support

### ISSUE THREAD

**Issue by appliedprivacy** [cloudalchemy/ansible-prometheus#296]
**What is missing?**

Your current role requires the ansible control machine to have internet access.
Some environments do not have any direct internet access for security reasons.
Would you accept PRs to make internet access optional?

**Comment by paulfantom** [comment]
Offline installation is already possible. Look into PR which implemented it: https://github.com/cloudalchemy/ansible-prometheus/pull/239 and our test case in https://github.com/cloudalchemy/ansible-prometheus/blob/master/molecule/alternative/prepare.yml and https://github.com/cloudalchemy/ansible-prometheus/blob/master/molecule/alternative/playbook.yml

**Comment by appliedprivacy** [comment]
great, thanks for the superfast reply. I assume this is the case for all your ansible roles then (specifically https://github.com/cloudalchemy/ansible-node-exporter)

**Comment by paulfantom** [comment]
I don't think this is propagated to all of them, but node-exporter has it already as you can specify `node_exporter_binary_local_dir`.

**Comment by appliedprivacy** [comment]
this role has offline support via `prometheus_binary_local_dir`, closing.
