### ISSUE TITLE
upstream ansible bug (to_nice_yaml): causes task "alerting rules file" to fail

### ISSUE THREAD

**Issue by appliedprivacy** [cloudalchemy/ansible-prometheus#297]
The following templates use the affected "to_nice_yaml" filter:

- [templates/alert.rules.j2](https://github.com/cloudalchemy/ansible-prometheus/blob/ec5c1c691ccc130c63f645572f6c394eea3e4ffc/templates/alert.rules.j2#L6) 
- [templates/prometheus.yml.j2](https://github.com/cloudalchemy/ansible-prometheus/blob/ec5c1c691ccc130c63f645572f6c394eea3e4ffc/templates/prometheus.yml.j2#L6)

therefore this role fails with the following errors (or similar)

```
FAILED! => {"changed": false, "msg": "AnsibleError: Unexpected templating type error occurred on ({{ ansible_managed | comment }}\n\ngroups:\n- name: ansible managed alert rules\n  rules:\n  {{ prometheus_alert_rules | to_nice_yaml(indent=2) | indent(2,False) }}\n): value must be a string"}
```

https://github.com/cloudalchemy/ansible-node-exporter/issues/158
upstream bug: https://github.com/ansible/ansible/issues/66916

Target system:
Debian 10

```
ansible 2.9.9
  config file = /home/user/.ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.7 (default, Mar 13 2020, 10:23:39) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
```

**Comment by paulfantom** [comment]
I don't see this as a bug in ansible role (role is using concepts described in ansible docs, and if a filter from those docs doesn't work, it is ansible problem, not role one). That said, let's track this in one place at https://github.com/cloudalchemy/ansible-node-exporter/issues/158

**Comment by appliedprivacy** [comment]
I see your point, but I would still have found this issue useful because it shows me known problem.
Even if the root-cause is outside the role, it make the role unusable without workarounds
and this issue could be a place for users to share their workarounds.
It does not look like we will be getting an upstream fix for this soon.
