### ISSUE TITLE
Cannot install prometheus when using "ec2_sd_config" with filter because of missing jmespath

### ISSUE THREAD

**Issue by lpysj** [cloudalchemy/ansible-prometheus#300]
**What happened?**
Trying to install prometheus with "ec2_sd_config" in scrape_config.

**Did you expect to see some different?**
I expected prometheus to get installed

**How to reproduce it (as minimally and precisely as possible)**:
Start a new playbook with just the prometheus role with the following var:
    prometheus_scrape_configs:
      - job_name: ec2
        ec2_sd_configs:
        - filters:
          - name: tag:Name
            values: "some name"

**Environment**

* Role version:

    `2.15.5`

* Ansible version information:

    `ansible 2.9.9`
    

* Variables:

```
insert role variables relevant to the issue
```

* Ansible playbook execution Logs:

```
TASK [cloudalchemy.prometheus : Get all file_sd files from scrape_configs] ********************************************************************************************************
fatal: [i-026fa58d22039cc72]: FAILED! => {"msg": "You need to install \"jmespath\" prior to running json_query filter"}

```

**Anything else we need to know?**:
JMESPATH is correctly installed on the machine.

**Comment by paulfantom** [comment]
Section [Requirements in README.md file](https://github.com/cloudalchemy/ansible-prometheus#requirements) specifies that `jmespath` is needed to run this role.
