### ISSUE TITLE
roles: - cloudalchemy.prometheus. Why?

### ISSUE THREAD

**Issue by melissajenner22** [cloudalchemy/ansible-prometheus#304]
**What did you do?**

Use https://github.com/cloudalchemy/ansible-prometheus to install prometheus.

cat playbook.yml
---
- hosts: all
  roles:
  - devops
  vars:
    prometheus_targets:
      node:
      - targets:
        - localhost:9100
        labels:
          env: devops

 **ansible-playbook -i hosts playbook.yml**

ERROR! the role 'devops' was not found in /home/deploy/opslab/ansible-prometheus/roles:/home/deploy/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/deploy/opslab/ansible-prometheus

The error appears to be in '/home/deploy/opslab/ansible-prometheus/playbook.yml': line 4, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
  - devops
    

My understand of role is that, Each role is a directory tree in itself. The role name is the directory name within the /roles directory." I changed the role to cloudalchemy.prometheus. Then, it works. But, I do not understand why. There is no folder of cloudalchemy.prometheus. Why the role must be cloudalchemy.prometheus?

cat playbook.yml
---
- hosts: all
  roles:
  - cloudalchemy.prometheus
  vars:
    prometheus_targets:
      node:
      - targets:
        - localhost:9100
        labels:
          env: devops

**Did you expect to see some different?**

**Environment**

* Role version:

    `Insert release version/galaxy tag or Git SHA here`

* Ansible version information:

    `ansible --version`
    

* Variables:

```
insert role variables relevant to the issue
```

* Ansible playbook execution Logs:

```
insert Ansible logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by paulfantom** [comment]
It seems like role `devops` cannot be found by ansible. This is not an issue related to cloudalchemy.prometheus role.

PS. Please use [code quoting](https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code) when pasting parts of code. Without it github can apply its formatting and it can be quite hard to decode what was the original message.
