### ISSUE TITLE
* [WARNING]: Unable to find 'prometheus/rules' in expected paths 

### ISSUE THREAD

**Issue by melissajenner22** [cloudalchemy/ansible-prometheus#305]
**What happened?**

Do not understand why got the WARNING below.

[WARNING]: Unable to find 'prometheus/targets' in expected paths 

ansible-playbook -i hosts playbook.yml

cat playbook.yml
---
- hosts: all
  roles:
  - cloudalchemy.prometheus
  vars:
    prometheus_targets:
      node:
      - targets:
        - localhost:9100
        labels:
          env: devops

**Did you expect to see some different?**

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Role version:

    `Insert release version/galaxy tag or Git SHA here`

* Ansible version information:

    `ansible --version`
    

* Variables:

```
insert role variables relevant to the issue
```

* Ansible playbook execution Logs:

```
insert Ansible logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by paulfantom** [comment]
This is an expected warning when not using mechanism from https://github.com/cloudalchemy/ansible-prometheus/blob/master/defaults/main.yml#L80-L81

**Comment by melissajenner22** [comment]
How do I use the alert rules? There is no rules folder.

 80 prometheus_alert_rules_files:
 81   - prometheus/rules/*.rules
 82
 83 prometheus_static_targets_files:
 84   - prometheus/targets/*.yml
 85   - prometheus/targets/*.json
 86
 87 prometheus_alert_rules:
 88   - alert: Watchdog
 89     expr: vector(1)
 90     for: 10m
 91     labels:
