### ISSUE TITLE
[WARNING]: Unable to find 'prometheus/targets' in expected paths (use -vvvvv to see paths)

### ISSUE THREAD

**Issue by melissajenner22** [cloudalchemy/ansible-prometheus#307]
**What did you do?**

git clone ansible-prometheus and ansible-node-exporter. Did not make any change.

**Did you expect to see some different?**
There are no targets in these folders below. How to solve it?

[**WARNING**]: **Unable** to find 'prometheus/targets' in expected paths (use -vvvvv to see paths)
looking for "prometheus/targets" at "ansible-prometheus/files/prometheus/targets"
looking for "prometheus/targets" at "ansible-prometheus/prometheus/targets"
looking for "prometheus/targets" at "ansible-prometheus/tasks/files/prometheus/targets"
looking for "prometheus/targets" at "ansible-prometheus/tasks/prometheus/targets"
looking for "prometheus/targets" at "playbooks/files/prometheus/targets"
looking for "prometheus/targets" at "playbooks/prometheus/targets"
looking for "prometheus/targets" at "playbooks/files/prometheus/targets"
looking for "prometheus/targets" at "playbooks/prometheus/targets"

**Environment**

* Role version:

    `Insert release version/galaxy tag or Git SHA here`

* Ansible version information:

    `ansible --version`
    

* Variables:

```
insert role variables relevant to the issue
```

* Ansible playbook execution Logs:

```
insert Ansible logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by till** [comment]
https://github.com/cloudalchemy/ansible-prometheus/blob/master/defaults/main.yml#L80-L85

This assumes you have files locally, which are copied to your server (running prometheus). If you don't have them, just supply an empty list.

E.g.:

```
prometheus_alert_rules_files: []
prometheus_static_targets_files: []
```

**Comment by till** [comment]
@paulfantom should these be empty lists — vs. now expecting paths that may not exist? I can PR if it helps.

**Comment by paulfantom** [comment]
I think we might need to rethink how `prometheus_alert_rules` works and maybe possibly delete it while focusing only on `prometheus_alert_rules_files`. This would simplify role a bit and we could always include set of basic alerts.

In case of `prometheus_static_targets_files` I think we should leave it as is. Current mechanism allows for fairly easy copying of static targets while also allowing to configure targets dynamically using ansible data and `prometheus_targets`. It would be good to add a note that this warning is expected though.

**Comment by till** [comment]
@paulfantom I had to _unset_ them with `[]` yesterday on another prometheus. Role failed otherwise. That's why I was asking. The prometheus is just collecting data to flush it up, therefor no rules. And all targets are generated from the Ansible run and SD.

**Comment by paulfantom** [comment]
By default both should be harmless: https://github.com/cloudalchemy/ansible-prometheus/blob/master/defaults/main.yml#L80-L85 I don't know why you had to unset them, more info would be appreciated. What was the role failure? Did prometheus start?

**Comment by till** [comment]
@paulfantom sorry, I missed this. But basically, ansible failed to provision (or the playbook failed to complete). I didn't test if prometheus would start, most likely it would as it doesn't need the files.

It just seems the ansible-role does. Or my ansible? I have this in a few places, where when there is a glob pattern defined by and the glob fails (because I don't have anything), ansible fails. Once I unset with `[]` the ansible run continues.
