### ISSUE TITLE
You need to install \"jmespath\" prior to running json_query filter

### ISSUE THREAD

**Issue by TheRojam** [cloudalchemy/ansible-prometheus#314]
**What happened?**

TASK [cloudalchemy.prometheus : Get all file_sd files from scrape_configs] ******************************
fatal: [mon-1-0-1.inet.lpz]: FAILED! => {"msg": "You need to install \"jmespath\" prior to running json_query filter"}

**Did you expect to see some different?**

that this role install its requirements to run?!

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Role version:

    `Insert release version/galaxy tag or Git SHA here`

* Ansible version information:

    `ansible --version`
  2.9.13

* Variables:

```
insert role variables relevant to the issue
```

* Ansible playbook execution Logs:

```
insert Ansible logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by paulfantom** [comment]
This is clearly stated in [requirements section](https://github.com/cloudalchemy/ansible-prometheus#requirements)
