### ISSUE TITLE
Failure with a few tasks in check mode

### ISSUE THREAD

**Issue by meons** [cloudalchemy/ansible-prometheus#322]
**What happened?**
In check mode, a few tasks fail.

**Did you expect to see some different?**
The play in check mode should not fail.

**How to reproduce it (as minimally and precisely as possible)**:
Simply run in check mode (`--check`)

**Environment**

* Role version:

    `2.16.2`

* Ansible version information:

    `2.10.3`
    

* Variables:

```
Default vars
```

* Ansible playbook execution Logs:

```
TASK [cloudalchemy.prometheus : create prometheus data directory] **************
fatal: [myhost]: FAILED! => {"changed": false, "gid": 0, "group": "root", "mode": "0755", "msg": "chown failed: failed to look up user prometheus", "owner": "root", "path": "/var/lib/prometheus", "size": 4096, "state": "directory", "uid": 0}
```

```
TASK [cloudalchemy.prometheus : ensure prometheus service is started and enabled] ***
fatal: [myhost]: FAILED! => {"changed": false, "msg": "Could not find the requested service prometheus: host"}
```

```
RUNNING HANDLER [cloudalchemy.prometheus : restart prometheus] *****************
fatal: [myhost]: FAILED! => {"changed": false, "msg": "Could not find the requested service prometheus: host"}
```

**Anything else we need to know?**:

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**
