### ISSUE TITLE
Installation tar url.

### ISSUE THREAD

**Issue by paulfantom** [cloudalchemy/ansible-prometheus#33]
Do we want to support different URL for prometheus, than one listed in https://github.com/cloudalchemy/ansible-prometheus/blob/master/tasks/install.yml#L34? If yes we should define this link as a variable in [defaults/main.yml](defaults/main.yml).

This is one of features in [@SuperQ roles](https://gitlab.com/superq/prometheus-ansible/blob/master/roles/prometheus/defaults/main.yml#L15)

**Comment by rdemachkovych** [comment]
If we have a case with a different URL then can add, but now I do not see any.
