### ISSUE TITLE
Multiple targets in scrape_configs

### ISSUE THREAD

**Issue by NoFWayMan** [cloudalchemy/ansible-prometheus#331]
I want to install node_exporter on several hosts. 
For example i have 3 hosts in inventory file, and i want that after i install prometheus - there will be all my hosts listed in targets, like this:
- targets:
     - host1:9100
     - host2:9100
     - host3:9100
How should i edit scrape_configs (defaults/main.yml) to have all hosts from my inventory file in targets.

I tried to use "for" loop

- "{% for host in groups['worker'] %}
{{ host + ':9100 ' }}
{% endfor %}"

But it makes a string like "- host1:9100 host2:9100 host3:9100"

Please help

**Comment by SuperQ** [comment]
See [this example](https://github.com/prometheus/demo-site/blob/9d0e3661e0f80878900df3c7a391bbb1702e9dbe/group_vars/prometheus.yml#L37).

**Comment by NoFWayMan** [comment]
Thanks! That helps a lot! My problom solved 👍
