### ISSUE TITLE
Define default data retention period

### ISSUE THREAD

**Issue by paulfantom** [cloudalchemy/ansible-prometheus#34]
Maybe this role should have variable which defines data retention period (like in [here](https://gitlab.com/superq/prometheus-ansible/blob/master/roles/prometheus/defaults/main.yml#L18)).
Or even go futher, and define most of configuration flags as ansible variables, and check their validity in [tasks/preflight.yml](tasks/preflight.yml) ?

**Comment by rdemachkovych** [comment]
Sounds fine and useful.
