### ISSUE TITLE
checksum failed because is not the good line selected in sha256sums.txt (when install prometheus)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [cloudalchemy/ansible-prometheus#356]
**What happened?**

When we have used the role with ansible 2.7.18, at all try we seen an error about checksum of prometheus downloaded file. After some search we find that:
- all files are correctly downloaded by the role
- the calculated checksum of file downloaded is available in `sha256sums.txt`
- but the role verifiy the first line of this file and not the good line with the arch we have on the server (role used to deploy on Debian 10)

**Did you expect to see some different?**

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Role version:

    `I don't know but we install role on 30/04/2021`

* Ansible version information:

    `2.7.18`
    `ansible installed with pip in venv`

* Variables:

```
insert role variables relevant to the issue
```

* Ansible playbook execution Logs:

```
insert Ansible logs relevant to the issue here
```

**Anything else we need to know?**:

To use role we have commented line `checksum: "sha256:{{ __prometheus_checksum }}"` in install.yml
After some other problem with have installed ansible 2.9.18 but not retry to install prometheus withou comment of this line (maybe its just a bug with ansible 2.7 (we don't know).

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**
