### ISSUE TITLE
prometheus_config_dir/consoles and prometheus_config_dir/console_libraries are inaccessible

### ISSUE THREAD

**Issue by mihaitodor** [cloudalchemy/ansible-prometheus#360]
This is a follow-up to #168.

I deployed this role on a RHEL8 box and it looks like UI is unable to display files from the `prometheus_config_dir/consoles` folder because it's owned by root:root with permissions 0644 (see [here](https://github.com/cloudalchemy/ansible-prometheus/blob/dbdb79feed9569e2c1f7f7b1d8ccb80cff025bbc/tasks/install.yml#L76-L80)). Once I changed the group to `prometheus`, `http://<hostname>:9090/consoles/node-disk.html` and others started working.

Could you please let me know why it was decided that the group should remain set to `root` as stated by @paulfantom [here](https://github.com/cloudalchemy/ansible-prometheus/issues/168#issuecomment-450015724)?

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**
