### ISSUE TITLE
Deprecation warning about `include`

### ISSUE THREAD

**Issue by lucc** [cloudalchemy/ansible-prometheus#373]
**What happened?**

When using this role I get the following deprecation warning:
```
[DEPRECATION WARNING]: "include" is deprecated, use include_tasks/import_tasks instead. 

This feature will be removed in version 2.16. Deprecation warnings can be disabled by 
setting deprecation_warnings=False in ansible.cfg.
```

**Did you expect to see some different?**

No deprecation warnings.

**How to reproduce it (as minimally and precisely as possible)**:

Use this playbook:
```yaml
- hosts: all
  roles: [cloudalchemy.prometheus]
``` 

**Environment**

* Role version:

4.0.0

* Ansible version information:

```
ansible [core 2.12.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/luc/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/luc/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.1 (main, Dec 11 2021, 17:22:55) [GCC 11.1.0]
  jinja version = 3.0.3
  libyaml = True
```

* Variables:

none

* Ansible playbook execution Logs:

none, the warning is displayed before anything else is done by the playbook.

**Anything else we need to know?**:

The relevant code seems to be here:
``` 
~/.ansible/roles/cloudalchemy.prometheus/tasks/main.yml
13:- include: preflight.yml
19:- include: install.yml
24:- include: configure.yml
```

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**
