### ISSUE TITLE
Selinux packages for Oracle Linux 8

### ISSUE THREAD

**Issue by foxsibirsky** [cloudalchemy/ansible-prometheus#389]
**What is missing?**
Selinux packages for Oracle Linux 8

**Why do we need it?**
For Oracle Linux support

**Environment**
Oracle Linux 8.5

* Role version: 1440ae7db7d40c749121bfbdec366100d7587bdf (current)

**Anything else we need to know?**:

Hello. I want to suggest Oracle Linux 8 support to the role, just add a new file to the **vars/oraclelinux-8.yml**
Hope, this helps to improve the role 

```
---
prometheus_selinux_packages:
  - python3-libselinux
  - policycoreutils-python-utils

```

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**
