### ISSUE TITLE
Installing from distribution repo

### ISSUE THREAD

**Issue by Yannik** [cloudalchemy/ansible-prometheus#392]
Hi,

as far as I could see in the playbooks, it is currently not supported to install prometheus from the main repository distribution repository of server (e.g. the debian packages repo). 

This may have been a good approach when prometheus was still in its infancy, but today you can get pretty mature versions of prometheus from repos. It has the benefit of staying up-to-date with regards to security much easier than having to carefully watch changelogs/cves (and then installing from source again).

Is this a deliberate design choice, or would you be open for a PR which supports installation from the distro repository?

Best regards
Yannik

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**
