### ISSUE TITLE
Add AlmaLinux variable file

### ISSUE THREAD

**Issue by mayorobadji** [cloudalchemy/ansible-prometheus#402]
**What is missing?**
A ansible_distribution variable for AlmaLinux.

**Why do we need it?**
Because the ansible distribution or os variable for AlmaLinux does not return centos-8.

**Environment**
AWS

* Role version:

2.16.1

* Ansible version information:

    `ansible --version`
ansible 2.9.15
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/mbadji/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov 16 2020, 22:23:17) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

**Anything else we need to know?**:

N/A

**Comment by mayorobadji** [comment]
Overriding the variable worked for me.
Adding a file name almalinux.yml (with the relevant variables) in my groups_vars directory did the trick.

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**
