### ISSUE TITLE
Is ansible-prometheus abandoned? No commits have been made since January 2022 (now October 2022)

### ISSUE THREAD

**Issue by louwrentius** [cloudalchemy/ansible-prometheus#404]
Should we consider this code abandoned / deprecated?

**Comment by artybdrlt** [comment]
Any news? Do you know any Ansible role / collection that is better updated now?

**Comment by kaufmo** [comment]
I think this is moved to https://github.com/prometheus-community/ansible

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**
