### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by paulfantom** [cloudalchemy/ansible-prometheus#56]
I would like to release 1.0 and have a feature-freezed, production version of this role.

@SuperQ @rdemachkovych do you think we are missing something or we need to refactor some part?

If there are things to do before 1.0.0 release, please mention them in this thread.

**Comment by SuperQ** [comment]
I have a few ideas, I'll file some issues.

**Comment by paulfantom** [comment]
I've added one more issue (#73) and this is probably last thing before 1.0.0.
