### ISSUE TITLE
Add default CriticalRAMLoad alert rules

### ISSUE THREAD

**Issue by rdemachkovych** [cloudalchemy/ansible-prometheus#63]
Add default CriticalRAMLoad alert rules

**Comment by sjal** [comment]
I had some previous version that still had RAM alerts, this one hasn't - apparently the PromQL changed a bit lately (as I remember rules to be working correctly) and both the CPU and RAM alerts have to be redone (why has been RAM alert removed anyway?)

**Comment by paulfantom** [comment]
It wasn't removed. We are still shipping this alert by default: https://github.com/cloudalchemy/ansible-prometheus/blob/a110f4ae78ad2784d644e1fcbe89474a2b6532e3/defaults/main.yml#L91-L98
